/**
 * Race01
 * Race01
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenDataAttributes from './TokenDataAttributes';

/**
 * The TokenData model module.
 * @module model/TokenData
 * @version 0.0.1
 */
class TokenData {
    /**
     * Constructs a new <code>TokenData</code>.
     * @alias module:model/TokenData
     * @param type {module:model/TokenData.TypeEnum} 
     * @param attributes {module:model/TokenDataAttributes} 
     */
    constructor(type, attributes) { 
        
        TokenData.initialize(this, type, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, attributes) { 
        obj['type'] = type;
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>TokenData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenData} obj Optional instance to populate.
     * @return {module:model/TokenData} The populated <code>TokenData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = TokenDataAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          TokenDataAttributes.validateJSON(data['attributes']);
        }

        return true;
    }


}

TokenData.RequiredProperties = ["type", "attributes"];

/**
 * @member {module:model/TokenData.TypeEnum} type
 */
TokenData.prototype['type'] = undefined;

/**
 * @member {module:model/TokenDataAttributes} attributes
 */
TokenData.prototype['attributes'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
TokenData['TypeEnum'] = {

    /**
     * value: "token"
     * @const
     */
    "token": "token"
};



export default TokenData;

