/**
 * Race01
 * Race01
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Token from './model/Token';
import TokenData from './model/TokenData';
import TokenDataAttributes from './model/TokenDataAttributes';
import TestApi from './api/TestApi';


/**
* Race01.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Race01 = require('index'); // See note below*.
* var xxxSvc = new Race01.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Race01.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Race01.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Race01.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The TokenData model constructor.
     * @property {module:model/TokenData}
     */
    TokenData,

    /**
     * The TokenDataAttributes model constructor.
     * @property {module:model/TokenDataAttributes}
     */
    TokenDataAttributes,

    /**
    * The TestApi service constructor.
    * @property {module:api/TestApi}
    */
    TestApi
};
