openapi: 3.0.1
info:
  title: Race01
  description: Race01
  version: 0.0.1
paths:
  /auth/reg:
    post:
      tags:
        - Auth
      summary: Login user
      description: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        '409':
          description: User with this username already exists
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/409/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/vnd.api+json:
              schema:
                description: 'Standard JSON:API error'
                type: array
                items:
                  type: object
                  required:
                    - errors
                  properties:
                    errors:
                      type: object
                      description: Non empty array of errors occurred during request processing
                      items:
                        type: object
                        required:
                          - code
                          - error
                        properties:
                          code:
                            type: string
                            description: Code is the application-specific error code
                            example: ERR_INVALID_CREDENTIALS
                          error:
                            type: string
                            description: Error is the application-specific error message
                            example: Invalid credentials
                          status:
                            type: integer
                            description: Status is the HTTP status code applicable to this problem
                            example: 400
                            enum:
                              - 400
                              - 401
                              - 403
                              - 404
                              - 409
                              - 500
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      description: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '404':
          description: User with this username does not exist
          content:
            application/json:
              schema:
                description: Requested resource does not exist.
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/paths/~1auth~1reg/post/responses/500/content/application~1vnd.api%2Bjson/schema'
        '409':
          description: first password and second password do not match
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/409/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
  /rooms:
    post:
      tags:
        - Rooms
      summary: Create room
      description: Create room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  required:
                    - id
                    - type
                    - attributes
                  properties:
                    id:
                      type: string
                      example: GroveStreet
                      description: Name of the room.
                    type:
                      type: string
                      enum:
                        - create_room
                      description: The type of the resource.
                    attributes:
                      type: object
                      required:
                        - password
                      properties:
                        password:
                          type: string
                          example: password123
                          description: The password of the room.
      responses:
        '201':
          description: Room created successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms~1%7BroomName%7D/patch/requestBody/content/application~1json/schema'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                description: One of the parameters is invalid. Refer to the response body for details.
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/paths/~1auth~1reg/post/responses/500/content/application~1vnd.api%2Bjson/schema'
        '409':
          description: Conflict with existing room
          content:
            application/json:
              schema:
                description: Conflict
                content:
                  application/vnd.api+json:
                    schema:
                      $ref: '#/paths/~1auth~1reg/post/responses/500/content/application~1vnd.api%2Bjson/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
  '/rooms/{roomName}':
    get:
      tags:
        - Rooms
      summary: Get room
      description: Get room by ID
      responses:
        '201':
          description: Room retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms~1%7BroomName%7D/patch/requestBody/content/application~1json/schema'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/404/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
    patch:
      tags:
        - Rooms
      summary: Close room
      description: Close room by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  required:
                    - id
                    - type
                    - attributes
                  properties:
                    id:
                      type: string
                      example: GroveStreet
                      description: Name of the room.
                    type:
                      type: string
                      enum:
                        - room
                      description: The type of the resource.
                    attributes:
                      type: object
                      required:
                        - status
                        - created_at
                        - players
                      properties:
                        status:
                          type: string
                          enum:
                            - waiting
                            - playing
                          description: The status of the room.
                        created_at:
                          type: string
                          format: date-time
                          description: The date and time when the room was created.
                          example: '2023-10-01T12:00:00Z'
                        players:
                          type: array
                          items:
                            type: string
                            description: The players usernames in the room.
                            example: janedoe
      responses:
        '200':
          description: Room updated successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms~1%7BroomName%7D/patch/requestBody/content/application~1json/schema'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/400/content/application~1json/schema'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/404/content/application~1json/schema'
        '409':
          description: Conflict with existing room
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/409/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
    delete:
      tags:
        - Rooms
      summary: Delete room
      description: Delete room by ID
      responses:
        '204':
          description: Room deleted successfully
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/404/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
  '/rooms/{roomName}/player':
    post:
      tags:
        - Room
      summary: Join room
      description: Join room by ID
      responses:
        '200':
          description: Room joined successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms~1%7BroomName%7D/patch/requestBody/content/application~1json/schema'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/400/content/application~1json/schema'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/404/content/application~1json/schema'
        '409':
          description: Conflict with existing room
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/409/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
    delete:
      tags:
        - Room
      summary: Leave room
      description: Leave room by ID
      responses:
        '201':
          description: Room left successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms~1%7BroomName%7D/patch/requestBody/content/application~1json/schema'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/400/content/application~1json/schema'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/404/content/application~1json/schema'
        '409':
          description: Conflict with existing room
          content:
            application/json:
              schema:
                $ref: '#/paths/~1rooms/post/responses/409/content/application~1json/schema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1reg/post/responses/500'
components:
  schemas:
    Token:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              example: johndoe
              description: The username of the user.
            type:
              type: string
              enum:
                - token
              description: The type of the resource.
            attributes:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  description: The JWT token for the user.
    Registration:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              example: johndoe
              description: The username of the user.
            type:
              type: string
              enum:
                - registration
              description: The type of the resource.
            attributes:
              type: object
              required:
                - password
                - password_confirmation
              properties:
                password:
                  type: string
                  example: password123
                  description: The password of the user.
                password_confirmation:
                  type: string
                  example: password123
                  description: The password confirmation of the user.
    Login:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required: '-id - type - attributes'
          properties:
            id:
              type: string
              example: johndoe
              description: The username of the user.
            type:
              type: string
              enum:
                - login
              description: The type of the resource.
            attributes:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  example: password123
                  description: The password of the user.
