openapi: 3.0.1
info:
  title: Race01
  description: Race01
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    Token:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - token
            attributes:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Refresh Token
