openapi: 3.0.1

info:
  title: Race01
  description: Race01
  version: 0.0.1

paths:
  /auth/reg:
    $ref: './paths/Registration.yaml'
  /auth/login:
    $ref: './paths/Login.yaml'

components:
  schemas:
    Token:
      $ref: './spec/components/schemas/Token.yaml'
    Registration:
      $ref: './spec/components/schemas/Registration.yaml'
    Login:
      $ref: './spec/components/schemas/Login.yaml'